main: ru.flametaichou.TempGroups
name: TempGroups
version: 0.5
author: flametaichou
description:

commands:
   ep:
      description: Основная команда плагина
      permission: tempgroups.*
      usage: /tg add|remove|reload|version|help
